spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demodb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 30

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/demodb
    user: postgres
    password: password
